# Generated by Django 2.1.7 on 2019-03-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default=None, help_text='Enter a book genre (e.g. Science Fiction)', max_length=200),
        ),
    ]
