# Generated by Django 2.1.7 on 2019-03-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_auto_20190310_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_photo',
            field=models.ImageField(blank=True, default=None, height_field='30', null=True, upload_to='static/library_app/images/book_covers', verbose_name='Book Cover', width_field='30'),
        ),
    ]
