# Generated by Django 2.1.5 on 2019-03-15 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_auto_20190310_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_photo',
        ),
    ]
